steps:
  - type: chroot
    cmd: "pacman -S --noconfirm xorg xorg-xinit pulseaudio pulseaudio-alsa intel-ucode xdg-user-dirs"

  - type: chroot
    cmd: "pacman -S --noconfirm i3-wm i3status i3blocks dmenu rofi picom feh network-manager-applet"

  - type: chroot
    cmd: "pacman -S --noconfirm lightdm lightdm-gtk-greeter"

  - type: service
    action: "enable"
    name: "lightdm"

  - type: chroot
    cmd: "xdg-user-dirs-update"

  - type: file
    path: "/mnt/home/${user}/.xinitrc"
    mode: "0755"
    template: |
      #!/bin/sh
      if [ -d /etc/X11/xinit/xinitrc.d ]; then
        for f in /etc/X11/xinit/xinitrc.d/*; do
          [ -x "$f" ] && . "$f"
        done
        unset f
      fi
      exec i3

  - type: file
    path: "/mnt/home/${user}/.config/i3/config"
    mode: "0644"
    template: |
      set $mod Mod4
      font pango:monospace 10
      bindsym $mod+Return exec alacritty
      bindsym $mod+d exec rofi -show drun
      bindsym $mod+Shift+e exec "i3-msg exit"
      exec --no-startup-id nm-applet
      exec --no-startup-id picom --no-vsync

  - type: chroot
    cmd: "chown -R ${user}:users /home/${user}/.xinitrc /home/${user}/.config"
