steps:
  - type: chroot
    cmd: "pacman -S --noconfirm xorg xorg-xinit pulseaudio pulseaudio-alsa intel-ucode xdg-user-dirs"

  - type: chroot
    cmd: "pacman -S --noconfirm ${video_drivers}"

  # XFCE
  - type: chroot
    cmd: "pacman -S --noconfirm xfce4 xfce4-goodies network-manager-applet pavucontrol"

  - type: chroot
    cmd: "pacman -S --noconfirm lightdm lightdm-gtk-greeter"

  - type: service
    action: "enable"
    name: "lightdm"

  - type: chroot
    cmd: "xdg-user-dirs-update"

  - type: file
    path: "/mnt/home/${user}/.xinitrc"
    mode: "0755"
    template: |
      #!/bin/sh
      #
      # ~/.xinitrc  — Executado pelo 'startx'
      if [ -d /etc/X11/xinit/xinitrc.d ]; then
        for f in /etc/X11/xinit/xinitrc.d/*; do
          [ -x "$f" ] && . "$f"
        done
        unset f
      fi
      exec startxfce4

  - type: file
    path: "/mnt/home/${user}/.gtkrc-2.0"
    mode: "0644"
    template: |
      style "xfdesktop-icon-view" {
        XfdesktopIconView::label-alpha = 0
        XfdesktopIconView::selected-label-alpha = 170

        base[NORMAL]   = "#cccccc"
        base[SELECTED] = "#cccccc"
        base[ACTIVE]   = "#cccccc"

        fg[NORMAL]   = "#ffffff"
        fg[SELECTED] = "#000000"
        fg[ACTIVE]   = "#000000"
      }
      widget_class "*XfdesktopIconView*" style "xfdesktop-icon-view"

  - type: chroot
    cmd: "chown -R ${user}:users /home/${user}/.xinitrc /home/${user}/.gtkrc-2.0"
